config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'countries' => 'pages#countries'
  get 'team' => 'pages#team'
  get 'countries/:iso' => 'dashboard#country', as: 'country'
  get 'map' => 'map#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'join'}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :alerts

  namespace :api, defaults: {format: :json}  do
    with_options :except => [:edit, :new] do |option|
      option.resources :users do
        option.resources :alerts , :only => [], :shallow => true do
          option.resources :alert_rankings, :path => "rankings"
          option.resources :alert_images, :only => :create, :path => "images"
        end
      end
      option.resources :alerts
    end
    resources :sessions, :only => [:create, :destroy]
  end

end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= image_tag 'scanforest-logo.png', height: '54', width: '237', alt: 'ScanForest' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home <span class="sr-only">(current)</span>'.html_safe, root_path %></li>
        <li><%= link_to 'Map', map_path %></li>
        <li><%= link_to 'Alerts', alerts_path %></li>
        <li><%= link_to 'Country Profile', countries_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="user_icon">&nbsp;<i class="fa fa-user"></i></span> <%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Another action</a></li>
            <li class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
          </ul>
        </li>
        <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>