config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'countries' => 'pages#countries'
  get 'team' => 'pages#team'
  get 'countries/:iso' => 'dashboard#country', as: 'country'
  get 'map' => 'map#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'join'}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :alerts

  namespace :api, defaults: {format: :json}  do
    with_options :except => [:edit, :new] do |option|
      option.resources :users do
        option.resources :alerts , :only => [], :shallow => true do
          option.resources :alert_rankings, :path => "rankings"
          option.resources :alert_images, :only => :create, :path => "images"
        end
      end
      option.resources :alerts
    end
    resources :sessions, :only => [:create, :destroy]
  end

end

app/views/pages/countries.html.erb
<h2><%= link_to 'Nicaragua', country_path(iso: 'nic') %></h2>

app/views/pages/index.html.erb
<div id="banner"></div>

<div id="main" class="container-fluid">
  <h1>Objectives</h1>
  <ul>
  <li>Develop an application to help monitor deforestation and forest degradation, and the reasons behind it.</li>
  <li>Obtain local data through crowdsourcing.</li>
  </ul>

  <iframe src="https://player.vimeo.com/video/125310978?title=0&byline=0&portrait=0" width="960" height="540" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

app/views/pages/map.html.erb
<div id="map">
	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d124838.77246075461!2d-86.2584606!3d12.097659!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1spt-BR!2sni!4v1428854221515" frameborder="0" style="border:0"></iframe>

	<div class="controllers">
		<!-- MySemiModal -->
		<div id="MySemiModal">
			<div class="title">Report Type</div>
			<div class="report_options">
				<a href="#" class="ball fire"><i></i><span class="text">Incendio</span></a>
				<a href="#" class="ball tree"><i></i><span class="text">Tala</span></a>
				<a href="#" class="ball bee"><i></i><span class="text">Plaga</span></a>
				
			</div>
		</div>
		<div class="add_report_div">
			<a href="#" title="add report" id="add_report">
				<span class="text"> Add Report</span>
				<span class="button">+</span>
			</a>
		</div>

		<!-- Modal -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="myModalLabel">Modal title</h4>
					</div>
					<div class="modal-body">
						...
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div>

		<script>
			jQuery(document).ready(function($) {
				$('#add_report').click(function(event) {
					$('#MySemiModal').toggle(300);
				});

			});
		</script>
		


	</div>
</div>

app/views/pages/team.html.erb
<div id="banner"></div>

<div id="main" class="container-fluid">
  <h1>Team Members</h1>
  <h3>Daniel Drake</h3>
  <p>Web front-end &amp; back-end</p>
  <h3>Darlon Espinoza</h3>
  <p>Web front-end &amp; back-end</p>
  <h3>Dennis Gallo</h3>
  <p>UX design &amp; thought leader</p>
  <h3>Hansel Miranda</h3>
  <p>Web front-end &amp; back-end, mobile app, project management</p>
  <h3>Gerardo Ortega</h3>
  <p>Web front-end &amp; back-end, sysadmin</p>
  <h3>Gustavo Rayo</h3>
  <p>Mobile app lead</p>
  <h3>Ronnie Rios</h3>
  <p>Web back-end</p>
  <h3>André Rocha</h3>
  <p>UI design, web front-end, video</p>
</div>