config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'countries' => 'pages#countries'
  get 'team' => 'pages#team'
  get 'countries/:iso' => 'dashboard#country', as: 'country'
  get 'map' => 'map#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_up => 'join'}, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :alerts

  namespace :api, defaults: {format: :json}  do
    with_options :except => [:edit, :new] do |option|
      option.resources :users do
        option.resources :alerts , :only => [], :shallow => true do
          option.resources :alert_rankings, :path => "rankings"
          option.resources :alert_images, :only => :create, :path => "images"
        end
      end
      option.resources :alerts
    end
    resources :sessions, :only => [:create, :destroy]
  end

end

app/models/alert.rb
# == Schema Information
#
# Table name: alerts
#
#  id          :integer          not null, primary key
#  lat         :float
#  lon         :float
#  magnitude   :integer
#  description :string
#  area        :float
#  created     :time
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  country_id  :integer
#  alert_type  :string
#

require 'twilio-ruby'

class Alert < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  belongs_to :user
  belongs_to :country
  has_many :alert_rankings
  has_many :alert_images, dependent: :delete_all
  attr_accessor :address

  validates_presence_of :lat, :lon, :alert_type, :magnitude, :user
  validates :lat, inclusion: { in: (-90..90), message: "Invalid latitude value" }
  validates :lon, inclusion: { in: (-180..180), message: "Invalid longitude value" }
  validates :magnitude, inclusion: { in: (1..10), message: "Invalid magnitud value" }
  validates :alert_type, inclusion: { in: %w(logging fire pest), message: "Invalid alert type" }

  #after_create :send_messages_to_technicians

  protected
  def send_messages_to_technicians
      client = Twilio::REST::Client.new
      User.technicians_messages.each do |user|
          client.messages.create({
	        :from => 'tuilio_number', 
	        :to => user.cell_phone, 
	        :body => 'A new alert was created',  
            })
      end
  end
  
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  load_and_authorize_resource
  def index
    @all_alerts = Alert.includes(:alert_images).all
    @my_alerts = @all_alerts.where(:user_id => current_user.id) if user_signed_in?
  end

  def new
  end
  
  def destroy
    @alert.destroy 
    redirect_to alerts_path
  end

  def create
    # Strong parameters doesn't support hashes with unknown keys, so we handle
    # that separately
    @alert = current_user.alerts.new(alert_params)
    @alert.save!
    @alert.alert_images.create!(uploaded_image: params[:alert][:image])
    redirect_to map_path
  end

private
  def alert_params
    params.require(:alert).permit(:lat, :lon, :magnitude, :area, :address, :description, :alert_type)
  end
end

app/controllers/api/alerts_controller.rb
module API
  class AlertsController < API::ApiController
      load_and_authorize_resource
      skip_before_action :authenticate_with_token!, only: [:index, :show]

      def index
        render json: Alert.all, status: :ok
      end

      def show
        render json: @alert, response: :ok
      end

      def create
        @alert = current_user.alerts.new(alert_params)
        if @alert.save
          render json: @alert, status: :created
        else
          render json: @alert.errors, status: :unprocessable_entity
        end
      end

      def update
        if @alert.update(alert_params)
          render json: @alert, status: :ok, location: [:api, @alert]
        else
          render json: @alert.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @alert.destroy
        head :ok
      end

      def alert_params
        params.require(:alert).permit(:lat, :lon, :magnitude, :description, :area, :created, :alert_type)
      end
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_alerts.html.erb
  <table class="table">
        <thead>
        <tr>
          <th width="120px"></th>
          <th width="120px">Type</th>
          <th width="200px">Magnitude</th>
          <th>Area</th>
          <th>Description</th>
          <th>Created at</th>
        </tr>
      </thead> 
      <tbody>
        <% alerts.each do |alert| %>
          <tr>
            <td><%= image_tag alert.alert_images.count > 0 ? alert.alert_images.last.uploaded_image.url : 'no-image-available.png', class: 'photo-thumb', alt:'No image' %></td>
            <td class="<%="#{alert.alert_type}type"%>"></td>
            <td class="rating-a">
            <select class="rating-bar" name="rating">
              <% (1..10).each do |x| %>
                <option value="<%=x%>" <%= selected="selected" if x==alert.magnitude %>></option>
              <% end %></select></td>
            <td><%= alert.area.present? ? "#{alert.area} acres" : "--" %></td>
            <td><%= alert.description %></td>
            <td><%= time_ago_in_words(alert.created_at) %></td>
            <% if own %>
              <td>
                <!--<%= link_to 'Edit', edit_alert_path(alert), :class => 'btn btn-mini' %>-->
                <%= link_to 'Destroy', alert_path(alert), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/alerts/index.html.erb
<style>
    .tab-content {
        color: #ffffff;
    }
    h1.ptitle {
        color: #76c949;
        font-size: 130%;
    }
    #col1 {
        width:400px;
        float:left;
        padding:5px 15px 5px 100px;
    }
    #col2 {
        width:350px;
        float:left;
        padding:10px;
    }
    #col3 {
        width:350px;
        float:left;
        padding:10px;
    }
</style>
<div id="country">
<div role="tabpanel">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">All</a></li>
        <% if user_signed_in? %>
        <li role="presentation"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">Own</a></li>
        <% end %>
      </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
     <%= @all_alerts.present? ? render(partial: "alerts", locals: { alerts: @all_alerts, own: false }) : "There's no alert to be displayed" %>
    </div>
    <div role="tabpanel" class="tab-pane" id="tab1">
     <%= @my_alerts.present? ? render(partial: "alerts", locals: { alerts: @my_alerts, own: true}) : "You haven't created any alert yet" %>
    </div>
  </div>
</div>
</div>

app/views/alerts/new.html.erb
<div id="banner"></div>

<h1>New alert</h1>

<%= form_for :alert, url: alerts_path do |f| %>
<p>
<%= f.label :lat, 'Latitude' %><br>
<%= f.text_field :lat %>
</p>

<p>
<%= f.label :lon, 'Longitude' %><br>
<%= f.text_field :lon %>
</p>

<p>
<%= f.label :magnitude, "Severity (1-10)" %><br>
<%= f.text_field :magnitude %>
</p>

<div id="reasons">
<%= f.label :description, "Reason" %><br>
<%= f.text_area :description, size: '25x2' %><br>
</div>

<p>
<%= f.label :area %><br>
<%= f.text_field :area %>
</p>

<p>
<%= f.label :image, "Upload a photo" %><br>
<%= f.file_field :image %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>